language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g codecov
script:
  - jest && codecov
env:
  # bucm-policy-search repository
  - secure: "Am/hqNtO3GFWI103KV0r79dYlecklJGHDfrEkLoiQRVAYuu3tkJShYSP2b89drWYKOJ6873UN0QQ1prDgtnoiOwmlYBk5iRGyDD5VvsvJyIK/NC1snrcT7XLAT5vgudhYm0p0OgrMEQFOlpuQwh+SFMuBpAP5Bvg4hy3Acpj+MmA5RSyCNEM1ju+y8fFNjG3vo7sj5puWT62oDyQ51gFRWpP3ePl1G36w/1QzKXCIniYm2hNIpGsFOEnImyiDZC5ULgCFXo3GGJg0PQyJRrcX2/eoEMww3YZnR58yfA8CHF9VbWGX03hG4ZSQar40niAKsBo0Ui1Ha3TwPqEnS/qQK/VMnIEu8MY/83/K3rfL5z39Rov32vB62qJT1nUE1yQ4nAVPpzkQWoEEJFahDadW5iJJ9Fch2ouoFV4entPV9mYsr5klMgpoPgP317nPbMTgbm/BKKMqQPZ0H95M820UZWItaHujaQ18A6s3JNSnHFYL6erMfsl1W2mN50lhPBbGHKMVem7Ydu4JkCdyxMPFHkAynN5qeMcXFdc/3S34hS/yAHEqvnE3msSdsVWYf8nN1UGKwbtkRvZIJC1sUdj+OeKueqg9ZW5rFR4Q3FGI6rnr7nOnWCbQedMX4u0NL8Syz8VKKMcyTkf12o9zYVHvqFoEmrh8uKt4p1Ybw+T7mA="

  # gricn Repository
  - secure: "HI8mq43j7rEN6FRK0XTHrwPSdiERCJd8bE6rvlgnabt1gQQwthLMmWCzP+dYMp4d9TgeszZeUbLm2hWOMfeaZSxTMkf1D6DKgqQlBthqsKplCs9pReIlHEUWWL3Fo8XfhYEMQoj7W32kwGvlsuBn1xLNvHnIzRbSwIq82Gf34qkj2pRuADnNHFhuTNYodklK4099S5Itown7bjyB6RaY9vB3DFyJ9Pr4xghyoQ7R8Q0bohiq2jCCWkkDVx8XbeWlFblzz/AxBZTgQqZDlAZ0OuT+vpWyq06uQJopDuQlCjttBNWpLt7pK59LaQbfJSWoIeNTVZasSttXpilE05Z0N8ZC22+X412OwM9N7IWZSpQtZc1WUXHeFj7YtVx5j9bioi+mWqNhfYU2RwvMtNmPOpQsUIlsG6UUVLb7b+7KsWSmEqxsK5WatZUVMPPdT1nlveRqUA4Qzqc8K9awB0o0L1+5II0JyqxE7257QOb1Ab6S9I4EpRSjFPM/L4UaS2cpjit7QmIjL6en2wbEJw2fIcY/vaZMUVkMLFBLotKq1s7W9SxGO97iFqx8WDNFQ3UcwW5SMm60GBCcxwcPHzLoF1qKWtA/eQMKla5+4WkvHxPI+J3HWhFbYNdwePDmgLEx2wbwc9Nv5F8AMee6LOEwnM0wUHueBp/uGgBk7bbha0s="
